# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GULayout.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.log_console_ = QtGui.QPlainTextEdit(self.centralwidget)
        self.log_console_.setGeometry(QtCore.QRect(10, 470, 781, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.log_console_.setFont(font)
        self.log_console_.setReadOnly(True)
        self.log_console_.setObjectName(_fromUtf8("log_console_"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(40, 20, 731, 367))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.splitter = QtGui.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.control_gbox_ = QtGui.QGroupBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_gbox_.sizePolicy().hasHeightForWidth())
        self.control_gbox_.setSizePolicy(sizePolicy)
        self.control_gbox_.setObjectName(_fromUtf8("control_gbox_"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.control_gbox_)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ctrl_on_board_ = QtGui.QRadioButton(self.control_gbox_)
        self.ctrl_on_board_.setObjectName(_fromUtf8("ctrl_on_board_"))
        self.horizontalLayout.addWidget(self.ctrl_on_board_)
        self.ctrl_software_ = QtGui.QRadioButton(self.control_gbox_)
        self.ctrl_software_.setChecked(True)
        self.ctrl_software_.setObjectName(_fromUtf8("ctrl_software_"))
        self.horizontalLayout.addWidget(self.ctrl_software_)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addWidget(self.control_gbox_)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.freq_label_text_ = QtGui.QLabel(self.widget1)
        self.freq_label_text_.setObjectName(_fromUtf8("freq_label_text_"))
        self.horizontalLayout_2.addWidget(self.freq_label_text_)
        self.freq_editor_ = QtGui.QLineEdit(self.widget1)
        self.freq_editor_.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.freq_editor_.setObjectName(_fromUtf8("freq_editor_"))
        self.horizontalLayout_2.addWidget(self.freq_editor_)
        self.freq_unit_text_ = QtGui.QLabel(self.widget1)
        self.freq_unit_text_.setObjectName(_fromUtf8("freq_unit_text_"))
        self.horizontalLayout_2.addWidget(self.freq_unit_text_)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.calibration_gbox_ = QtGui.QGroupBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibration_gbox_.sizePolicy().hasHeightForWidth())
        self.calibration_gbox_.setSizePolicy(sizePolicy)
        self.calibration_gbox_.setObjectName(_fromUtf8("calibration_gbox_"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.calibration_gbox_)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.calib_sar1_ca_ = QtGui.QCheckBox(self.calibration_gbox_)
        self.calib_sar1_ca_.setCheckable(True)
        self.calib_sar1_ca_.setChecked(True)
        self.calib_sar1_ca_.setObjectName(_fromUtf8("calib_sar1_ca_"))
        self.verticalLayout.addWidget(self.calib_sar1_ca_)
        self.calib_sar2_cm_ = QtGui.QCheckBox(self.calibration_gbox_)
        self.calib_sar2_cm_.setChecked(True)
        self.calib_sar2_cm_.setObjectName(_fromUtf8("calib_sar2_cm_"))
        self.verticalLayout.addWidget(self.calib_sar2_cm_)
        self.calib_sar2_ca_ = QtGui.QCheckBox(self.calibration_gbox_)
        self.calib_sar2_ca_.setObjectName(_fromUtf8("calib_sar2_ca_"))
        self.verticalLayout.addWidget(self.calib_sar2_ca_)
        self.calib_sar_ca_ = QtGui.QCheckBox(self.calibration_gbox_)
        self.calib_sar_ca_.setObjectName(_fromUtf8("calib_sar_ca_"))
        self.verticalLayout.addWidget(self.calib_sar_ca_)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_6.addWidget(self.calibration_gbox_)
        self.operation_gbox_ = QtGui.QGroupBox(self.widget1)
        self.operation_gbox_.setObjectName(_fromUtf8("operation_gbox_"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.operation_gbox_)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.signal_process = QtGui.QComboBox(self.operation_gbox_)
        self.signal_process.setObjectName(_fromUtf8("signal_process"))
        self.verticalLayout_5.addWidget(self.signal_process)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.operation_gbox_)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox = QtGui.QSpinBox(self.operation_gbox_)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_3.addWidget(self.spinBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.opt_sample_start_btn_ = QtGui.QPushButton(self.operation_gbox_)
        self.opt_sample_start_btn_.setObjectName(_fromUtf8("opt_sample_start_btn_"))
        self.verticalLayout_5.addWidget(self.opt_sample_start_btn_)
        self.verticalLayout_6.addWidget(self.operation_gbox_)
        self.verticalLayout_7.addWidget(self.splitter)
        self.widget_2 = QtGui.QWidget(self.splitter_2)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.log_console_.raise_()
        self.widget.raise_()
        self.control_gbox_.raise_()
        self.widget.raise_()
        self.widget_2.raise_()
        self.label.raise_()
        self.spinBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_FIle = QtGui.QMenu(self.menubar)
        self.menu_FIle.setObjectName(_fromUtf8("menu_FIle"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.menu_FIle.addAction(self.actionOpen_Project)
        self.menubar.addAction(self.menu_FIle.menuAction())
        self.freq_label_text_.setBuddy(self.freq_editor_)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.control_gbox_.setTitle(_translate("MainWindow", "Control", None))
        self.ctrl_on_board_.setText(_translate("MainWindow", "Ob-board", None))
        self.ctrl_software_.setText(_translate("MainWindow", "Software", None))
        self.freq_label_text_.setText(_translate("MainWindow", "Frequency", None))
        self.freq_unit_text_.setText(_translate("MainWindow", "MHz", None))
        self.calibration_gbox_.setTitle(_translate("MainWindow", "Calibration", None))
        self.calib_sar1_ca_.setText(_translate("MainWindow", "SAR1 Calibration", None))
        self.calib_sar2_cm_.setText(_translate("MainWindow", "SAR2 CM Calibration", None))
        self.calib_sar2_ca_.setText(_translate("MainWindow", "SAR2 Calibration", None))
        self.calib_sar_ca_.setText(_translate("MainWindow", "SAR Calibration", None))
        self.operation_gbox_.setTitle(_translate("MainWindow", "Operation", None))
        self.label.setText(_translate("MainWindow", "Sample Count:", None))
        self.opt_sample_start_btn_.setText(_translate("MainWindow", "Start", None))
        self.menu_FIle.setTitle(_translate("MainWindow", "&Project", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

